### ISSUE TITLE
Proper place to specify what prediction is

### ISSUE THREAD

**Issue by hose314** [instacart/lore#138]
Hi @montanalow!

In order to make any PR to contribute to this repo I'd like to understand few concepts of Lore.

Where is exactly proper place to specify what prediction is. For example we have instance of XGBoost classifier
```py
class_estimator = XGBoostClassifier()
```
then we can make inference by calling `class_estimator.predict()` if we want to get class label or `class_estimator.predict_proba()` in order to get probability estimation of classes (in regression problem we could get real value output). 

Instance of Lore Model has his own predict method that could be called in different places (e.g https://github.com/instacart/lore/blob/bc3646e49b10a53079473a8e12478979ee0dedd0/lore/www/__init__.py#L53)

So if we want to get probability estimation of classes and use flask as the serving method, then we have to override predict here at the lore model level https://github.com/instacart/lore/blob/master/lore/models/base.py#L133

But if we want to use build-in tools like `shap_explainer` within the same model  https://github.com/instacart/lore/blob/master/lore/models/base.py#L371
then we have to override predict method at the lore estimator level https://github.com/instacart/lore/blob/master/lore/estimators/__init__.py#L27

Finally, my question is where the proper place to specify what output prediction is? 
I'm confused bc at the lore model level there is `predict_proba` method https://github.com/instacart/lore/blob/master/lore/models/base.py#L143 

Thanks!

**Comment by montanalow** [comment]
If I understand correctly, your ultimate goal may be to expose `predict_proba` via flask. In that case, I'd suggest adding a second flask endpoint to `predict_proba` that is similar to `predict` here: https://github.com/instacart/lore/blob/master/lore/www/__init__.py#L43

Most of the time, we override predict at the model level. Models abstract the encoding/decoding of raw input data w/ the pipeline before/after the estimator makes it's prediction, so the caller doesn't need to be aware of that transformation step. 

Another reason for the separation between model/estimator is that the estimators prediction might not be the final desired application level result. For example, one model I created uses the estimator to predict distances between points, and the model uses the predicted distances to solve the traveling salesman problem, returning an ordered sequence of the input data points by shortest route, instead of decoded distances between all points from the estimator.

`shap_explainer` should be useful without overriding predict for any of the `Estimator` sub-classes that come with lore. All `Estimator` sub-classes must define predict, per the abstract base class.

@ganesh-krishnan Has more context on specific examples of `predict_proba`. I think the current implementation is slightly inconsistent because it doesn't handle encoding/decoding at the model level and just does a pass through to the estimator. We may want to amend that, but the functionality was originally created for a naive estimator example:  https://github.com/instacart/lore/pull/127

**Comment by hose314** [comment]
Thanks, @montanalow! I think I get it now :)
