### ISSUE TITLE
'module' object has no attribute 'keras'  in python2.7

### ISSUE THREAD

**Issue by B4yesC4t** [instacart/lore#70]
I create a new project with command: 
`lore init test_subscribers --python-version=2.7.13 --keras`

I set my python path as `~/.pyenv/versions/test_subscribers/bin/python`.

Then I follow the cute little example.But when I run tests with `lore test`, there is an Import error.

```
ERROR: unit.test_subscribers (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_subscribers
Traceback (most recent call last):
  File "/home/wang/.pyenv/versions/2.7.13/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/home/wang/.pyenv/versions/2.7.13/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/wang/code/ml/lore_subscribers/tests/unit/test_subscribers.py", line 15, in <module>
    from lore_subscribers.models.subscribers import DeepName, BoostedName
  File "/home/wang/code/ml/lore_subscribers/lore_subscribers/models/subscribers.py", line 20, in <module>
    class DeepName(lore.models.keras.Base):
AttributeError: 'module' object has no attribute 'keras'
```

There is result of run `lore pip list|grep Keras`:

```
Keras (2.1.4)
```

**Comment by montanalow** [comment]
@B4yesC4t Thanks for the report. I've patched master and updated the readme to reflect the full requirements. One problem is naming your app with `test_subscribers` and naming your model the same as your app. This causes a unit test for your model to conflict with the app module, since they are both `test_subscribers`. I recommend starting fresh with a new lore installation from master, and new app name not prefixed with `test_`, or following the guide on medium which is now linked in the Readme.

**Comment by montanalow** [comment]
https://tech.instacart.com/how-to-build-a-deep-learning-model-in-15-minutes-a3684c6f71e

https://github.com/instacart/lore/commit/3a8b20e658531c9bec3280f9c2939b0a10644ba9
